/* ============================================================
   ChromaMimic — exporters: .cube / .xmp / .dng / .png
   Ported verbatim from the original build; only brand strings,
   preset names and filenames changed to ChromaMimic.
   ============================================================ */
import { s2l, type ColorGrade, type Grade, type Method, type Space } from "./color-engine";
import { applyLUTToImage } from "./image";

const BRAND = "ChromaMimic";
const STUDIO = "Nunik Co.";

export function dl(blob: Blob, name: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 4000);
}

/* ---------- .cube (Adobe Cube LUT v1.0) ---------- */
export function lutToCube(
  lut: Float32Array,
  size: number,
  title: string,
  meta: { method: Method; space: Space },
): string {
  let s = `# Generated by ${BRAND} (${STUDIO})\n`;
  s += `# Method: ${meta.method} | Input space: ${
    meta.space === "log" ? "see note below" : "sRGB / Rec.709"
  } | Built: ${new Date().toISOString().slice(0, 10)}\n`;
  if (meta.space === "log")
    s += `# NOTE: frames were tagged as log. Apply a Color Space Transform (log -> Rec.709) BEFORE this LUT, or results will look wrong.\n`;
  s += `TITLE "${title}"\nLUT_3D_SIZE ${size}\nDOMAIN_MIN 0.0 0.0 0.0\nDOMAIN_MAX 1.0 1.0 1.0\n`;
  const lines: string[] = [];
  for (let i = 0; i < lut.length; i += 3) {
    lines.push(`${lut[i].toFixed(6)} ${lut[i + 1].toFixed(6)} ${lut[i + 2].toFixed(6)}`);
  }
  return s + lines.join("\n") + "\n";
}

/* ---------- .xmp (Lightroom / ACR preset, grade only) ---------- */
export function exportXMP(g: Grade) {
  const v = (x: number, m: number) => Math.round(x * m);
  const xmp = `<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"
   crs:Version="15.0" crs:ProcessVersion="11.0"
   crs:Temperature="${v(g.temp, 2000) >= 0 ? "+" : ""}${v(g.temp, 2000)}"
   crs:Tint="${v(g.tint, 50)}"
   crs:Exposure2012="${(g.exp * 1.5).toFixed(2)}"
   crs:Contrast2012="${v(g.con, 100)}"
   crs:Highlights2012="${v(g.hig, 100)}"
   crs:Shadows2012="${v(g.sha, 100)}"
   crs:Saturation="${v(g.sat, 100)}"
   crs:Vibrance="${v(g.vib, 100)}"
   crs:Blacks2012="${v(g.fad, 40)}"
   crs:HasSettings="True">
   <crs:Name><rdf:Alt><rdf:li xml:lang="x-default">${BRAND} Grade</rdf:li></rdf:Alt></crs:Name>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>`;
  dl(new Blob([xmp], { type: "application/rdf+xml" }), `chromamimic_grade_${Date.now()}.xmp`);
}

/* ---------- .xmp from the colour wheels (Lightroom ColorGrade tags) ---------- */
export function exportColorGradeXMP(cg: ColorGrade) {
  const i = (n: number) => Math.round(n);
  const xmp = `<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"
   crs:Version="15.0" crs:ProcessVersion="11.0" crs:HasSettings="True"
   crs:ColorGradeShadowHue="${i(cg.shadows.hue)}"
   crs:ColorGradeShadowSat="${i(cg.shadows.sat)}"
   crs:ColorGradeShadowLum="${i(cg.shadows.lum)}"
   crs:ColorGradeMidtoneHue="${i(cg.midtones.hue)}"
   crs:ColorGradeMidtoneSat="${i(cg.midtones.sat)}"
   crs:ColorGradeMidtoneLum="${i(cg.midtones.lum)}"
   crs:ColorGradeHighlightHue="${i(cg.highlights.hue)}"
   crs:ColorGradeHighlightSat="${i(cg.highlights.sat)}"
   crs:ColorGradeHighlightLum="${i(cg.highlights.lum)}"
   crs:ColorGradeGlobalHue="${i(cg.global.hue)}"
   crs:ColorGradeGlobalSat="${i(cg.global.sat)}"
   crs:ColorGradeGlobalLum="${i(cg.global.lum)}"
   crs:ColorGradeBlending="${i(cg.blending)}"
   crs:ColorGradeBalance="${i(cg.balance)}">
   <crs:Name><rdf:Alt><rdf:li xml:lang="x-default">${BRAND} Colour Grade</rdf:li></rdf:Alt></crs:Name>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>`;
  dl(new Blob([xmp], { type: "application/rdf+xml" }), `chromamimic_colorgrade_${Date.now()}.xmp`);
}

/* ---------- minimal LinearRaw DNG writer (16-bit, uncompressed) ---------- */
export function buildDNG(canvas: HTMLCanvasElement): Blob {
  const w = canvas.width,
    h = canvas.height;
  const px = canvas.getContext("2d")!.getImageData(0, 0, w, h).data;
  // ColorMatrix1 = XYZ(D65) -> sRGB linear (our "camera" is sRGB)
  const CM = [3.2406, -1.5372, -0.4986, -0.9689, 1.8758, 0.0415, 0.0557, -0.204, 1.057];
  const enc = (str: string) => {
    const b: number[] = [];
    for (let i = 0; i < str.length; i++) b.push(str.charCodeAt(i));
    b.push(0);
    if (b.length & 1) b.push(0);
    return b;
  };
  const make = enc(STUDIO),
    model = enc(BRAND),
    soft = enc(`${BRAND} (${STUDIO})`),
    ucm = enc(BRAND);
  const entries: {
    tag: number;
    type: number;
    count: number;
    inlineBytes: number[] | null;
    extMarker: { bytes: number[]; offset?: number } | null;
  }[] = [];
  const SHORT = 3,
    LONG = 4,
    RATIONAL = 5,
    ASCII = 2,
    BYTE = 1,
    SRATIONAL = 10;
  function bytesLong(v: number) {
    return [v & 255, (v >> 8) & 255, (v >> 16) & 255, (v >>> 24) & 255];
  }
  function bytesShort2(a: number, b = 0) {
    return [a & 255, (a >> 8) & 255, b & 255, (b >> 8) & 255];
  }
  const extBuf: { bytes: number[]; offset?: number }[] = [];
  function extOffsetPlaceholder(bytes: number[]) {
    const marker = { bytes } as { bytes: number[]; offset?: number };
    extBuf.push(marker);
    return marker;
  }
  const bps = extOffsetPlaceholder([16, 0, 16, 0, 16, 0]);
  const sf = extOffsetPlaceholder([1, 0, 1, 0, 1, 0]); // SampleFormat unsigned int
  const cmBytes: number[] = [];
  for (const x of CM) {
    const num = Math.round(x * 1000000) | 0,
      den = 1000000;
    cmBytes.push(
      num & 255,
      (num >> 8) & 255,
      (num >> 16) & 255,
      (num >>> 24) & 255,
      den & 255,
      (den >> 8) & 255,
      (den >> 16) & 255,
      (den >>> 24) & 255,
    );
  }
  const cm = extOffsetPlaceholder(cmBytes);
  const asn = extOffsetPlaceholder([
    1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
  ]); // AsShotNeutral 3 rational = 1
  const mkE = extOffsetPlaceholder(make),
    mdE = extOffsetPlaceholder(model),
    sfE = extOffsetPlaceholder(soft),
    ucmE = extOffsetPlaceholder(ucm);
  const imgBytes = new Uint8Array(w * h * 3 * 2);
  for (let i = 0, j = 0; i < px.length; i += 4) {
    for (let c = 0; c < 3; c++) {
      const lin = s2l(px[i + c] / 255);
      const u = Math.max(0, Math.min(65535, Math.round(lin * 65535)));
      imgBytes[j++] = u & 255;
      imgBytes[j++] = (u >> 8) & 255;
    }
  }
  const imgMarker = extOffsetPlaceholder(Array.from(imgBytes));

  function E(
    tag: number,
    type: number,
    count: number,
    inlineBytes: number[] | null,
    extMarker?: { bytes: number[]; offset?: number },
  ) {
    entries.push({ tag, type, count, inlineBytes, extMarker: extMarker ?? null });
  }
  E(254, LONG, 1, bytesLong(0));
  E(256, LONG, 1, bytesLong(w));
  E(257, LONG, 1, bytesLong(h));
  E(258, SHORT, 3, null, bps);
  E(259, SHORT, 1, bytesShort2(1));
  E(262, SHORT, 1, bytesShort2(34892)); // LinearRaw
  E(271, ASCII, make.length, null, mkE);
  E(272, ASCII, model.length, null, mdE);
  E(273, LONG, 1, null, imgMarker); // StripOffsets -> image data
  E(277, SHORT, 1, bytesShort2(3));
  E(278, LONG, 1, bytesLong(h)); // RowsPerStrip
  E(279, LONG, 1, bytesLong(w * h * 3 * 2)); // StripByteCounts
  E(284, SHORT, 1, bytesShort2(1));
  E(305, ASCII, soft.length, null, sfE);
  E(339, SHORT, 3, null, sf); // SampleFormat
  E(50706, BYTE, 4, [1, 4, 0, 0]); // DNGVersion
  E(50707, BYTE, 4, [1, 3, 0, 0]); // DNGBackwardVersion
  E(50708, ASCII, ucm.length, null, ucmE); // UniqueCameraModel
  E(50717, SHORT, 1, bytesShort2(65535)); // WhiteLevel
  E(50721, SRATIONAL, 9, null, cm); // ColorMatrix1
  E(50728, RATIONAL, 3, null, asn); // AsShotNeutral
  E(50778, SHORT, 1, bytesShort2(21)); // CalibrationIlluminant1 = D65

  const n = entries.length;
  const ifdStart = 8;
  const ifdSize = 2 + n * 12 + 4;
  let extPos = ifdStart + ifdSize;
  for (const m of extBuf) {
    if (extPos & 1) extPos++;
    m.offset = extPos;
    extPos += m.bytes.length;
  }
  const total = extPos;
  const buf = new Uint8Array(total);
  const dv = new DataView(buf.buffer);
  buf[0] = 0x49;
  buf[1] = 0x49;
  dv.setUint16(2, 42, true);
  dv.setUint32(4, ifdStart, true);
  dv.setUint16(ifdStart, n, true);
  let p = ifdStart + 2;
  for (const e of entries) {
    dv.setUint16(p, e.tag, true);
    dv.setUint16(p + 2, e.type, true);
    dv.setUint32(p + 4, e.count, true);
    if (e.extMarker) {
      dv.setUint32(p + 8, e.extMarker.offset!, true);
    } else {
      for (let k = 0; k < 4; k++) buf[p + 8 + k] = e.inlineBytes![k] || 0;
    }
    p += 12;
  }
  dv.setUint32(ifdStart + 2 + n * 12, 0, true); // next IFD = 0
  for (const m of extBuf) {
    buf.set(Uint8Array.from(m.bytes), m.offset!);
  }
  return new Blob([buf], { type: "image/x-adobe-dng" });
}

/* ---------- format-aware download ---------- */
export type ExportFormat = "cube" | "png" | "dng" | "xmp";

export function downloadCube(
  lut: Float32Array,
  size: number,
  title: string,
  meta: { method: Method; space: Space },
) {
  const txt = lutToCube(lut, size, title, meta);
  dl(new Blob([txt], { type: "text/plain" }), `chromamimic_${size}cube_${Date.now()}.cube`);
}

export function downloadPNG(img: HTMLImageElement, lut: Float32Array, size: number) {
  const c = applyLUTToImage(img, lut, size, 4096);
  c.toBlob((b) => b && dl(b, `chromamimic_graded_${Date.now()}.png`), "image/png");
}

export function downloadDNG(img: HTMLImageElement, lut: Float32Array, size: number) {
  const c = applyLUTToImage(img, lut, size, 3000);
  dl(buildDNG(c), `chromamimic_graded_${Date.now()}.dng`);
}
