import HoverReveal from "./ui/hover-reveal";
import { Reveal } from "./ui/Reveal";

/* The tool is the proof: a real original, a real reference, and the graded
   result the engine produced from them. The stills live in /public/samples
   and were generated by scripts/gen-demo.ts with the same colour engine the
   in-browser tool runs. */
const BEFORE = "/samples/demo-before.jpg";
const AFTER = "/samples/demo-after.jpg";
const REFERENCE = "/samples/demo-reference.jpg";

const SPECS = [
  { k: "Original", v: "Alpine lake, cool neutral" },
  { k: "Reference", v: "Warm 35mm street still" },
  { k: "Match", v: "Blend · 85% · 33³ .cube" },
];

export function LookDemo() {
  return (
    <section id="demo" className="mx-auto max-w-[1180px] scroll-mt-24 px-5 pt-6 md:px-8 md:pt-10">
      <Reveal className="mx-auto max-w-2xl text-center">
        <p className="eyebrow mb-3">Real frames · real engine</p>
        <h2 className="text-[clamp(26px,3.6vw,40px)]">Run your pointer over the frame.</h2>
        <p className="mx-auto mt-3 max-w-xl text-[15px] leading-relaxed text-muted">
          A cool, neutral original. A warm film still as the reference. ChromaMimic learned the
          transform between the two and applied it to the original. What you reveal is the exported
          result, not a mock-up.
        </p>
      </Reveal>

      <Reveal delay={0.08} className="mt-10">
        <HoverReveal
          before={BEFORE}
          after={AFTER}
          alt="A boathouse on an alpine lake beneath cloud-wrapped peaks"
          className="rounded-[var(--radius-lg)] border border-hairline-2 shadow-lg"
        >
          {/* The reference still: what the original was matched to. */}
          <figure className="pointer-events-none absolute bottom-3 left-3 z-20 m-0 hidden w-[148px] overflow-hidden rounded-[6px] border border-white/15 bg-black/55 p-1 backdrop-blur-sm sm:block md:w-[176px]">
            <img
              src={REFERENCE}
              alt="Reference still: a cream Mercedes wagon under wisteria, warm film colours"
              className="block aspect-[3/2] w-full rounded-[4px] object-cover"
              loading="lazy"
              decoding="async"
              draggable={false}
            />
            <figcaption className="px-1 pb-0.5 pt-1.5 font-mono text-[9.5px] uppercase tracking-wider text-white/85 sm:text-[10px]">
              Reference look
            </figcaption>
          </figure>
        </HoverReveal>
      </Reveal>

      <Reveal delay={0.12} className="mt-4 flex items-center gap-3 sm:hidden">
        <img
          src={REFERENCE}
          alt="Reference still: a cream Mercedes wagon under wisteria, warm film colours"
          className="block h-12 w-[72px] shrink-0 rounded-[4px] border border-hairline-2 object-cover"
          loading="lazy"
          decoding="async"
          draggable={false}
        />
        <p className="text-[13px] leading-snug text-muted">
          <span className="font-mono text-[10.5px] uppercase tracking-wider text-faint">Reference look</span>
          <br />
          The warm street still the original was matched to.
        </p>
      </Reveal>

      <Reveal
        delay={0.14}
        className="mt-5 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"
      >
        <dl className="m-0 flex flex-wrap gap-x-7 gap-y-2 font-mono text-[11px] uppercase tracking-wider">
          {SPECS.map((s) => (
            <div key={s.k} className="flex items-baseline gap-2">
              <dt className="text-faint">{s.k}</dt>
              <dd className="m-0 text-muted">{s.v}</dd>
            </div>
          ))}
        </dl>
        <a href="#tool" className="text-[13.5px] text-accent transition-colors hover:text-accent-hi">
          Try it with your own frames ↓
        </a>
      </Reveal>
    </section>
  );
}
